//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qwe
{
    using System;
    using System.Collections.Generic;
    
    public partial class cabinet
    {
        public int id { get; set; }
        public string namecab { get; set; }
        public Nullable<int> id_korpus { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<int> id_typecab { get; set; }
        public Nullable<System.DateTime> datarezerva { get; set; }
        public Nullable<System.DateTime> konecrezerva { get; set; }
        public string photo { get; set; }
    
        public virtual korpus korpus { get; set; }
        public virtual status status { get; set; }
        public virtual typecabinet typecabinet { get; set; }
        public virtual User User { get; set; }
    }
}
