//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qwe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rezervEntities2 : DbContext
    {
        public rezervEntities2()
            : base("name=rezervEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cabinet> cabinet { get; set; }
        public virtual DbSet<korpus> korpus { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<typecabinet> typecabinet { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserCabinet> UserCabinet { get; set; }
    }
}
