//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qwe
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCabinet
    {
        public int id { get; set; }
        public Nullable<int> cabinetID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    
        public virtual cabinet cabinet { get; set; }
        public virtual User User { get; set; }
    }
}
